plugin: aws_ec2
regions: 
  - "us-east-1"
keyed_groups:
  - key: tags.Name
    separator: "_"
    prefix: my

  - prefix: instance_type
    key: instance_type

# filters:
#   instance-state-name: running
#   tag:lesson: ansible

compose:
  ansible_host: public_ip_address
  foo: private_ip_address
  boo: instance_id
  key: key_name