---
- name: create a user using a variable
  #hosts: all
  hosts: my_node_1_clarusway
  become: true
  vars:
    user: lisa
  tasks:
    - name: create a user {{ user }}
      user:
        name: "{{ user }}"

    - debug:
        msg: "private_ip is {{ foo }}"

    - debug:
        msg: "instance_id is {{ boo }}"

    - debug:
        msg: "my key pem is {{ key }}"

    - debug:
        msg: "host is {{ ansible_host }}"