apiVersion: v1
clusters:
- cluster:
    server: https://1.2.3.4
  name: development
- cluster:
    server: https://5.6.7.8
  name: scratch
contexts:
- context:
    cluster: development
    user: developer
  name: dev-frontend
- context:
    cluster: development
    user: developer
  name: dev-storage
- context:
    cluster: scratch
    user: experimenter
  name: exp-scratch
current-context: dev-storage
kind: Config
preferences: {}
users:
- name: developer
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
- name: experimenter
  user:
    password: some-password
    username: exp